### PR TITLE
MikroORM v6 compatibility

### LINKED ISSUE #5: Support for Mikro ORM V6
Mikro ORM [removed the `@Subscriber()`](https://mikro-orm.io/docs/upgrading-v5-to-v6#removed-subscriber-decorator) decorator requiring manually registering subscribers causing the `SoftDeletableHandlerSubscriber` to break.

Is there plans to support Mikro ORM v6?

### PR DESCRIPTION
**Pull request by Tucker-Eric**
Allows compatibility with MikroORM v6 (closes #5 )

Notable changes made for V6:

- Added node version requirement to `package.json` [Node 18.12+ is required](https://mikro-orm.io/docs/upgrading-v5-to-v6#node-1812-required)
- Upgraded TypeScript: [Typescript 5.0+ required](https://mikro-orm.io/docs/upgrading-v5-to-v6#%EF%B8%8F-typescript-50-required)
- Added a static `register` to `SoftDeletable` to be able to register `SoftDeletable` as a [MikroORM extension](https://mikro-orm.io/docs/upgrading-v5-to-v6#orm-extensions)
  - `register` registers the `SoftDeletableHandlerSubscriber`

Due to all these updates required by `v6` there is a very high likelihood backwards compatibility won't be preserved for some implementations of `mikro-orm-soft-delete`

### CODE REVIEW

**Comment by Char2sGu** [comment]
Awesome updates! @Tucker-Eric I'll merge it soon after making some small changes to it.

**Review by Char2sGu — APPROVED** [review]
Great work @Tucker-Eric

**Comment by Tucker-Eric** [comment]
@TheNightmareX The one thing I wish I could of done but couldn't see a path to implement was get the `@SoftDeletable` decorator to throw an error if the subscriber wasn't registered. If you're able to see a path forward/point me in the right direction, I could open a follow up PR.

**Comment by Char2sGu** [comment]
Hey @Tucker-Eric let's continue this discussion in #7 as this is out of the scope of this ticket.

**Pull request merged**
