### PR TITLE
Maintenance, tests and `fieldValue` to allow more control over the filter

### PR DESCRIPTION
**Pull request by AdriVanHoudt**
I know this is a lot for 1 pr and I will add some more tests still, but let me know if you'd want to merge this (in any form) otherwise we'd have to publish our own version (which is not an issue but I'd rather have 1 version of this)

### CODE REVIEW

**Comment by Char2sGu** [comment]
I appreciate it very much. I’ll review it asap

**Review by Char2sGu — APPROVED** [review]

**Comment by Char2sGu** [comment]
@AdriVanHoudt Thanks for your great efforts. I have made some updates on this PR, but would need you to `Allow edits by maintainers` in order to push to this thread. Do you mind doing it?

**Comment by AdriVanHoudt** [comment]
@TheNightmareX awesome!
I don't see that option on this pr, maybe because I forked it into our org and not my personal account.
Can't you apply the updates after merging?

**Comment by Char2sGu** [comment]
Then I won’t be able to squash commit it as a feature, but it’s fine, will do.

**Comment by Char2sGu** [comment]
@AdriVanHoudt Checkout the docs for the new feature. The option has been renamed to `valueInitial`. https://github.com/TheNightmareX/mikro-orm-soft-delete/tree/v0.2.0#valueinitial-option

**Pull request merged**
